# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-29 06:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Athlete',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('best100', models.FloatField()),
                ('best200', models.FloatField()),
            ],
        ),
    ]
