# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-29 06:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0002_athlete'),
    ]

    operations = [
        migrations.AddField(
            model_name='athlete',
            name='best10k',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='athlete',
            name='best1500',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='athlete',
            name='best400',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='athlete',
            name='best5k',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='athlete',
            name='best800',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='athlete',
            name='bestHM',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='athlete',
            name='bestMar',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='athlete',
            name='bestMile',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='best100',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='best200',
            field=models.FloatField(default=0),
        ),
    ]
